// PACOTE
package GUI;

// IMPORTA AS CLASSES
import Beans.MensagemDAO;
import Model.Mensagem;
import Model.Usuario;
import facebook4j.Facebook;
import facebook4j.FacebookException;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import twitter4j.Twitter;
import twitter4j.User;

public class Frame_TelaInicial extends javax.swing.JFrame {

// DECLARA AS VARIAVEIS 
    private Twitter t;
    private User eu;
    private Facebook f;
    private facebook4j.User uf;
    private Usuario usuarioLogado;
    private String palavra_chave;

// CONSTRUTOR
    public Frame_TelaInicial(Twitter t, User eu, Usuario usuarioLogado, Facebook f, facebook4j.User uf) {
        this.t = t;
        this.eu = eu;
        this.f = f;
        this.uf = uf;
        this.usuarioLogado = usuarioLogado;
        initComponents();
        URL url = this.getClass().getResource("/Imagens/favicon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTimeLine = new javax.swing.JMenu();
        menuBusca = new javax.swing.JMenu();
        menuInteracao = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();
        lbNomeUsuario = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TopSearch - Menu Principal");
        setFont(new java.awt.Font("Exotc350 Bd BT", 0, 10)); // NOI18N
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuTimeLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_timeline.png"))); // NOI18N
        menuTimeLine.setText("TimeLine");
        menuTimeLine.setToolTipText("Visualize sua TimeLine");
        menuTimeLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTimeLineMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuTimeLine);

        menuBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_busca.png"))); // NOI18N
        menuBusca.setText("Busca");
        menuBusca.setToolTipText("Realize uma busca social");
        menuBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBuscaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBusca);

        menuInteracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_interação.png"))); // NOI18N
        menuInteracao.setText("Interação");
        menuInteracao.setToolTipText("Visualize as mensagens de interação automática");
        menuInteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInteracaoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuInteracao);

        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_sobre.png"))); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.setToolTipText("Veja sobre o TopSearch");
        menuSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSobre);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone_fechar.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.setToolTipText("Sair do TopSearch");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        lbNomeUsuario.setText("NomeUsuarioLogado");
        lbNomeUsuario.setToolTipText("Usuário Logado");
        lbNomeUsuario.setEnabled(false);
        jMenuBar1.add(lbNomeUsuario);

        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// AO ABRIR A TELA, SETA NO LABEL NOMEUSUARIO O USUARIO LOGADO
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lbNomeUsuario.setText("Usuário Logado: " + usuarioLogado.getNome() + " " + usuarioLogado.getSobrenome());
    }//GEN-LAST:event_formWindowOpened
// MENU TIMELINE
    private void menuTimeLineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTimeLineMouseClicked

        // QUANDO O MENU TIMELINE ESTÁ ATIVO
        if (menuTimeLine.isEnabled()) {
            // REMOVE O CONTEUDO ABAIXO DO MENU
            this.getContentPane().removeAll();
            this.getContentPane();
            // CRIA DUAS COLUNAS E UMA LINHA
            this.setLayout(new GridLayout(1, 2));
            // CRIA UM PANEL EM BRANCO 
            JPanel p2 = new JPanel();
            // ADICIONAR O PANEL CRIADO DUAS VEZES NO PANEL PRINCIPAL PARA LIMPAR A TELA
            this.add(p2);
            this.add(p2);
            // SETA O TIPO DA TELA PARA FECHAR AO SAIR
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            // JOGA O PANEL PRINCIPAL COMO VISIVEL
            this.setVisible(true);
            this.getContentPane().removeAll();
            // SETA MENU INTERAÇÃO COMO ATIVO
            menuInteracao.setEnabled(true);
            // SETA MENU BUSCA COM O TEXTO BUSCA E ATIVO
            menuBusca.setText("Busca");
            menuBusca.setEnabled(true);
            // INSTANCIA OS PANELS P1 (TWITTER) E P2 (FACEBOOK)
            Panel_TTimeline p1 = new Panel_TTimeline(t, eu);
            Panel_FTimeline p3 = null;
            try {
                p3 = new Panel_FTimeline(f, uf);
            } catch (FacebookException ex) {
                ex.getMessage();
            }

            // SETA UMA BORDA SUPERIOR NOS 2 PANELS INSTANCIADOS
            p1.setBorder(new EmptyBorder(5, 0, 0, 0));
            p3.setBorder(new EmptyBorder(5, 0, 0, 0));
            // PEGA O CONTEUDO ATUAL DO PANEL
            this.getContentPane();
            // CRIA DUAS COLUNAS E UMA LINHA
            this.setLayout(new GridLayout(1, 2));
            // ADICIONA OS DOIS PANELS INSTANCIADOS NO PANEL PRINCIPAL
            this.add(p1);
            this.add(p3);
            // SETA O TIPO DA TELA PARA FECHAR AO SAIR
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            // JOGA O PANEL PRINCIPAL COMO VISIVEL
            this.setVisible(true);
            // INATIVA O MENU TIMELINE
            menuTimeLine.setEnabled(false);
            // SETA O FOCO NO MENU SUPERIOR
            jMenuBar1.setFocusable(true);
        }
    }//GEN-LAST:event_menuTimeLineMouseClicked

    private void menuInteracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInteracaoMouseClicked
        // QUANDO O MENU INTERAÇÃO ESTÁ ATIVO
        if (menuInteracao.isEnabled()) {
            menuTimeLine.setEnabled(true);
            // REMOVE O CONTEUDO ABAIXO DO MENU
            this.getContentPane().removeAll();
            // SETA MENU INTERAÇÃO COMO ATIVO
            menuInteracao.setEnabled(true);
            // SETA MENU BUSCA COM O TEXTO BUSCA E ATIVO
            menuBusca.setText("Busca");
            menuBusca.setEnabled(true);
            // INSTANCIA O PANEL P1 (INTERAÇÃO AUTOMATICA)
            Panel_InteracaoAutomatica p1 = new Panel_InteracaoAutomatica(usuarioLogado);
            // SETA UMA BORDA SUPERIOR NO PANEL INSTANCIADO
            p1.setBorder(new EmptyBorder(25, 0, 0, 0));
            // PEGA O CONTEUDO ATUAL DO PANEL
            this.getContentPane();
            // CRIA UMA UNICA COLUNA E LINHA
            this.setLayout(new GridLayout(1, 1));
            // ADICIONA O PANEL INSTANCIADO NO PANEL PRINCIPAL
            this.add(p1);
            // SETA O TIPO DA TELA PARA FECHAR AO SAIR
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            // JOGA O PANEL PRINCIPAL COMO VISIVEL
            this.setVisible(true);
            // INATIVA O MENU INTERAÇÃO AUTOMATICA
            menuInteracao.setEnabled(false);
            // SETA O FOCO NO MENU SUPERIOR
            jMenuBar1.setFocusable(true);

            // INTANCIA UM OBJETO MENSAGEM DAO
            MensagemDAO mensagemDao = new MensagemDAO();
            // INSTANCIA UM OBJETO MENSAGEM
            Mensagem mensagens = null;
            // RECUPERA AS MENSAGENS (NO MAXIMO CINCO) ARMAZENADAS NO BANCO DE DADOS, 
            // PASSANDO O USUARO LOGADO
            mensagens = mensagemDao.obterMensagens(usuarioLogado);
            // SE O RETORNO FOR DIFERENTE DE ZERO
            if (mensagens.getId() != 0) {
                // SETA O LABEL NOVOSERVICO PARA SERVIÇO EXISTENTE
                p1.lbNovoServico.setText("Serviço Existente");
                // SETA O RADIOBOX ATIVADO COMO MARCADO;
                if (mensagens.getStatus().equals("S")) {
                    p1.rdAtivado.setSelected(true);
                } // SETA O RADIOBOX DESATIVADO COMO MARCADO;
                else {
                    p1.rdDesativado.setSelected(true);
                }
                // SETA AS CINCO MENSAGENS NOS CAMPOS CORRESPONTES
                p1.txtMsg1.setText(mensagens.getMensagem1());
                p1.txtMsg2.setText(mensagens.getMensagem2());
                p1.txtMsg3.setText(mensagens.getMensagem3());
                p1.txtMsg4.setText(mensagens.getMensagem4());
                p1.txtMsg5.setText(mensagens.getMensagem5());
            } // SENÃO, SETA O LABEL NOVOSERVICO PARA SERVIÇO INEXISTENTE
            else {
                p1.lbNovoServico.setText("Serviço Inexistente");
            }
        }
    }//GEN-LAST:event_menuInteracaoMouseClicked

    // MENU SOBRE
    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        menuInteracao.isEnabled();
        try {
            // ABRE O BROWSER
            java.awt.Desktop.getDesktop().browse(new java.net.URI("http://www.topsearch.com.br/sobre"));
        } // TRATA OS ERROS EM CASO DE EXISTENCIA
        catch (URISyntaxException ex) {
            ex.getMessage();
        } catch (IOException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_menuSobreMouseClicked
    // MENU SAIR
    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        //FINALIZA A APLICAÇÃO
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

// MENU BUSCA
    private void menuBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBuscaMouseClicked
        // QUANDO O MENU BUSCA ESTÁ ATIVO
        if (menuBusca.isEnabled()) {
            // REMOVE O CONTEUDO ABAIXO DO MENU
            this.getContentPane().removeAll();
            // SETA MENU INTERAÇÃO E TIMELINE COMO ATIVOS
            menuTimeLine.setEnabled(true);
            menuInteracao.setEnabled(true);
            // PEGA O CONTEUDO ATUAL DO PANEL
            this.getContentPane();
            // CRIA DUAS COLUNAS E UMA LINHA
            this.setLayout(new GridLayout(1, 1));
            // CRIA UM PANEL EM BRANCO 
            JPanel p2 = new JPanel();
            // ADICIONAR O PANEL CRIADO DUAS VEZES NO PANEL PRINCIPAL PARA LIMPAR A TELA
            this.add(p2);
            this.add(p2);
            // SETA O TIPO DA TELA PARA FECHAR AO SAIR
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            // JOGA O PANEL PRINCIPAL COMO VISIVEL
            this.setVisible(true);

            // SE O MENU BUSCA ESTIVER COM O TEXTO BUSCA AVANÇADA
            if (menuBusca.getText().equals("Busca Avançada")) {
                // REMOVE O CONTEUDO ABAIXO DO MENU
                this.getContentPane().removeAll();
                // PEGA O CONTEUDO ATUAL DO PANEL
                this.getContentPane();
                // TWITTER
                // INSTANCIA A TELA DA BUSCA AVANCAÇADA DO TWITTER 
                Panel_BuscaAvanc p1 = new Panel_BuscaAvanc(t, eu, f, uf, palavra_chave, usuarioLogado);
                // SETA UMA BORDA SUPERIOR NO 2 PANEL INSTANCIADO
                p1.setBorder(new EmptyBorder(25, 0, 0, 0));
                // PEGA O CONTEUDO ATUAL DO PANEL
                this.setLayout(new GridLayout(1, 1));
                this.add(p1);
                // SETA O TIPO DA TELA PARA FECHAR AO SAIR
                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                // JOGA O PANEL PRINCIPAL COMO VISIVEL
                this.setVisible(true);
                // ATIVA O MENU BUSCA E SETA O TEXTO PARA BUSCA
                menuBusca.setEnabled(true);
                menuBusca.setText("Busca");
            } else {
                // SOLICITA UMA PALAVRA-CHAVE AO USUARIO 
                palavra_chave = JOptionPane.showInputDialog(null, "Informe a palavra-chave", "Busca Social", JOptionPane.INFORMATION_MESSAGE);
                // SE A PALAVRA CHAVE NÃO FOR EM BRANCO  
                if (palavra_chave.trim() != null) {
                    // INSTANCIA A TELA DE BUSCA TWITTER
                    Panel_TBusca p1 = new Panel_TBusca(t, eu, palavra_chave, usuarioLogado, "", "", "");
                    // SETA UMA BORDA SUPERIOR NO PANEL INSTANCIADO
                    p1.setBorder(new EmptyBorder(25, 0, 0, 0));
                    // INSTANCIA A TELA DA BUSCA NO FACEBOOK
                    Panel_FBusca p3;
                    try {
                        // SETA OS PARAMETROS DO CONSTRUTOR
                        p3 = new Panel_FBusca(f, uf, palavra_chave, usuarioLogado, "", "", "");
                        // SETA UMA BORDA SUPERIOR NO PANEL INSTANCIADO
                        p3.setBorder(new EmptyBorder(1025, 0, 0, 0));
                        // PEGA O CONTEUDO ATUAL DO PANEL
                        this.getContentPane();
                        // REMOVE O CONTEUDO 
                        this.getContentPane().removeAll();
                        // CRIA DUAS COLUNAS E UMA LINHA
                        this.setLayout(new GridLayout(1, 2));
                        // ADICIONA OS DOIS PANELS INSTANCIADOS NO PANEL PRINCIPAL
                        this.add(p1);
                        this.add(p3);
                    } // EM CASO DE ERRO 
                    catch (FacebookException ex) {
                        ex.getMessage();
                    }
                    // SETA O TIPO DA TELA PARA FECHAR AO SAIR
                    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    // JOGA O PANEL PRINCIPAL COMO VISIVEL
                    this.setVisible(true);
                    // SETA O FOCO O MENU BUSCA E ALTERA O TEXTO PARA BUSCA AVANÇADA
                    menuBusca.setText("Busca Avançada");
                    jMenuBar1.setFocusable(true);
                } // METODO RECURSIVO, ATE FUTURA ALTERAÇÃO
                else {
                    // CHAMA ESTE MESMO METODO
                    menuBuscaMouseClicked(evt);
                }
            }
        }
    }//GEN-LAST:event_menuBuscaMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            ex.getMessage();
        } catch (InstantiationException ex) {
            ex.getMessage();
        } catch (IllegalAccessException ex) {
            ex.getMessage();
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            ex.getMessage();
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu lbNomeUsuario;
    private javax.swing.JMenu menuBusca;
    private javax.swing.JMenu menuInteracao;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenu menuTimeLine;
    // End of variables declaration//GEN-END:variables
}
